// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi4QCR4QX9GWWomhB6ie0x4RHTL9wKlDc',
    appId: '1:939975981878:web:2ebb03f15dd02b0a66d197',
    messagingSenderId: '939975981878',
    projectId: 'digi-harmoni',
    authDomain: 'digi-harmoni.firebaseapp.com',
    storageBucket: 'digi-harmoni.firebasestorage.app',
    measurementId: 'G-JTPMTN9KBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4pPVqUabJmseuxyTCOeY6IIJJF-wMDC0',
    appId: '1:939975981878:android:aa25ea51af95050866d197',
    messagingSenderId: '939975981878',
    projectId: 'digi-harmoni',
    storageBucket: 'digi-harmoni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKqgyEzyOYiqdhCbf5o3VF1cgcbzZwoCc',
    appId: '1:939975981878:ios:09d6e633de9b3a1b66d197',
    messagingSenderId: '939975981878',
    projectId: 'digi-harmoni',
    storageBucket: 'digi-harmoni.firebasestorage.app',
    iosBundleId: 'com.example.digiHarmoni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKqgyEzyOYiqdhCbf5o3VF1cgcbzZwoCc',
    appId: '1:939975981878:ios:09d6e633de9b3a1b66d197',
    messagingSenderId: '939975981878',
    projectId: 'digi-harmoni',
    storageBucket: 'digi-harmoni.firebasestorage.app',
    iosBundleId: 'com.example.digiHarmoni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi4QCR4QX9GWWomhB6ie0x4RHTL9wKlDc',
    appId: '1:939975981878:web:b6f1dda8c7a7744366d197',
    messagingSenderId: '939975981878',
    projectId: 'digi-harmoni',
    authDomain: 'digi-harmoni.firebaseapp.com',
    storageBucket: 'digi-harmoni.firebasestorage.app',
    measurementId: 'G-FSY0PTMGRC',
  );
}
